### PR TITLE
broadcastserver

### PR DESCRIPTION
**Pull request by LFSaw**
+ added Helpfile
+ adapt from `OSCresponder` to `OSCFunc`
+ `BroadcastServer.for(s).asTarget.server` now returns `a BroadcastServer`

### CODE REVIEW

**Comment by telephon** [comment]
looks good. Have you thought through the consistency with the `Node` subclasses?

**Comment by LFSaw** [comment]
can you point me towards the `Node` subclasses you mean?

Reason for the change is that `asTarget.server` is used in `Steno` to determine the server to which a group is sent. returning `homeserver` breaks compatibility.

**Comment by telephon** [comment]
I was only slightly unsure about what happens if you use that group as a target for a synth or another group.

**Comment by LFSaw** [comment]
since steno uses this functionality extensively and I am using this patch since I created the PR, it is likely that it works.

**Comment by telephon** [comment]
ok. i guess we have to review broadcast server anyhow once we get multiple clients working correctly in server.

**Comment by telephon** [comment]
let's wait for the second review by @adcxyz

**Comment by LFSaw** [comment]
Having this in would really make my day.

**Pull request merged**
